src/config.js, src/containers/ListingPage/components/CoverGrid.jsx, src/containers/ListingPage/components/CoverList.jsx, src/containers/ListingPage/listingSagas.js, src/shapes.js, src/util/listingHelpers.js, src/util/listingSorter.js
Oppdatert for å reflektere endringene i listing-api i [denne pull requesten](https://github.com/NDLANO/listing-api/pull/18)
=> #529: adjust to updated api format

Dockerfile, src/server/routes/defaultRoute.js
Fixes NDLANO/Issues#2095
Fjerner noe redux-saga kode som kræsjet i ssr. Vi kan også lage en sak på å fjerne all redux-saga kode siden det ikke brukes lengre etter #53
=> 2095 ssr fix

src/containers/ListingPage/ListingPage.jsx
=> 2096 filter url fix

src/util/__tests__/listingHelpers-test.js, src/util/listingHelpers.js
Tar endelig høgde for at kolon må være på plass.
=> Better regexp to match format

src/containers/App/App.jsx, src/containers/ListingPage/ListingPage.jsx, src/containers/ListingPage/listingApi.js, src/i18n.js, src/phrases/phrases-nn.js, src/util/localeHelpers.js
https://github.com/NDLANO/Issues/issues/2183
=> added language selector and created phrases-nn

package.json, src/containers/ListingPage/ListingPage.jsx, src/containers/ListingPage/NotionDialog.jsx, src/containers/ListingPage/listingApi.js, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/util/listingHelpers.js, yarn.lock
Fixes NDLANO/Issues#2110
Fixes NDLANO/Issues#2152
Det dukker opp veldig få nye forklaringer etter man trykker 'Last mer' uten å ha valgt fag eller filter siden de fleste forklaringer i test blir filtrert bort fordi de ikke har fag. Bør dette fikses eller er det bra nok data i prod til at det ikke gjør noe? Finner ingen god måte å løse det på.
=> 2110 search in api

package.json, src/client.jsx
Fixes NDLANO/Issues#2211
Løst på samme måte som i ndla-frontend
=> Store language selection

src/containers/ListingPage/ListingPage.jsx
=> Make language selector always visible

src/containers/ListingPage/LicenseBox.jsx, src/containers/ListingPage/ListingPage.jsx, src/containers/ListingPage/NotionDialog.jsx, src/containers/ListingPage/listingApi.js
Fixes NDLANO/Issues#2315
Reimplementerer søk i concept-api istedenfor filtrering av lastet liste.
=> 2315: Reimplementing search from concept-api

src/containers/ListingPage/ListingPage.jsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js
=> 2377 embed url med iframe

src/api/concept/conceptApiInterfaces.ts, src/components/Concept/ConceptPage.jsx
Ved visning av en forklaring skal det vises en liste med artikler dersom det finnes.
Forklaringer som kan brukes:
Flere artikler: /?concept=743
Ingen artikler: /?concept=603
=> Concept displays list of related articles

src/server/contentSecurityPolicy.js
La til
'*.static.hotjar.com',
'*.hotjar.com',
=> Oppdaterer policy for å kjøre hotjar

src/server/contentSecurityPolicy.js
Guttorm trenger hotjar for måling.
=> Added hotjar urls, copied from ndla-frontend

src/components/Concept/ConceptPage.jsx
Fixes NDLANO/Issues#2469
Omskrivning av https://github.com/NDLANO/listing-frontend/pull/89
Funksjonalitet er uendret.
=> Rewrite: getArticles now handles 404 when fetching unpublished articles

src/client.jsx
Bruker localstorage for lagring av språk.
=> Stop using cookies

src/components/Concept/ConceptPage.jsx, src/components/Concept/VisualElement.tsx, src/components/LicenseBox.jsx, src/gqlSchema.json, src/interfaces.ts, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js, src/queries.ts, src/server/contentSecurityPolicy.js
Fixes NDLANO/Issues#2508
Depends on https://github.com/NDLANO/article-converter/pull/242, https://github.com/NDLANO/graphql-api/pull/162
Test:
* Trykk på en forklaring
* Trykk 'Bruk innhold'
* Sjekk at visuelt element har lisensinformasjon og at alt ser riktig ut
=> 2508 visualelement license info

src/containers/ListingPage/ListingView.tsx, src/phrases/phrases-en.js, src/phrases/phrases-nb.js, src/phrases/phrases-nn.js
Fixes https://github.com/NDLANO/Issues/issues/2623
Lagt til logikk for å hente ut embedkode med filtre på fag. 
Test ved: 
- velg fag
- kopier embed-code
- undersøke om embed-code gir riktige verdier
=> Now able to copy embedcode for subjects filters

package.json, src/api/article/articleApi.ts, src/api/image/imageApi.ts, src/components/Concept/ConceptPage.jsx, src/components/Concept/VisualElement.tsx, src/components/LicenseBox.jsx, src/interfaces.ts, src/queries.ts, src/util/getCopyrightCopyString.js, yarn.lock
Dependent på https://github.com/NDLANO/graphql-api/pull/177 
- Forandret på visualelement displaying slik at den fungerer med den nye typen/objektet som returneres av graphql
- Forandret apollo-client til statisk versjon, bumping til ny minor vil breake applikasjon
=> Fix new visual element type graphql

README.md, codegen.yml, package.json, src/components/Concept/VisualElement.tsx, src/containers/ListingPage/ListingContainer.tsx, src/containers/ListingPage/ListingPage.tsx, src/containers/ListingPage/ListingView.tsx, src/gqlSchema.json, src/graphqlTypes.ts, src/interfaces.ts, src/queries.ts, yarn.lock
Autogenererte type for GraphQL
Tilsvarende https://github.com/NDLANO/ndla-frontend/pull/784
=> Autogenerate gql types

src/components/Concept/VisualElement.tsx, src/components/LicenseBox.jsx, src/graphqlTypes.ts, src/queries.ts, src/util/getCopyrightCopyString.js
Gjør det slik at forfatter vises både i forklaringsdialog og under regler for bruk.
Test:
* Åpne pr og finn fram Aluminium
* Sjekk at forfatter vises både i lisenslinja og under informasjon om bruk av tekst.
=> Use creators rather than authors

src/components/Concept/VisualElement.tsx
Fixes NDLANO/Issues#3000
Viser manglende film på https://liste.ndla.no/nn/?concept=3088
For å teste må du kjøre lokalt med NDLA_ENVIRONMENT=prod, eller finne en anna forklaring med brightcove som visuelt element.
=> Bruker url direkte på visuelt element.

src/client.tsx, src/components/Concept/ConceptPage.tsx, src/components/Concept/VisualElement.tsx, src/components/CopyTextButton.tsx, src/components/Footer.tsx, src/components/LicenseBox.tsx, src/components/Matomo.tsx, src/components/PostResizeMessage.tsx, src/containers/App/App.tsx, src/containers/ListingPage/ListingContainer.tsx, src/containers/ListingPage/ListingPage.tsx, src/containers/ListingPage/ListingView.tsx, src/containers/NotFoundPage/NotFoundPage.tsx, src/server/helpers/Html.jsx, src/server/routes/defaultRoute.js, tsconfig.json
Samme som https://github.com/NDLANO/ndla-frontend/pull/915, bare her.
=> Switched over to automatic runtime for jsx transform

src/components/LicenseBox.tsx, src/gqlSchema.json, src/graphqlTypes.ts
Avhengig av og merges samtidig som https://github.com/NDLANO/graphql-api/pull/237
=> Update graphql. Fix typing

now.json, package.json, src/server/helpers/Html.tsx, src/server/routes/defaultRoute.tsx, yarn.lock
Fixes https://github.com/NDLANO/Issues/issues/2994
Så løsningen mens jeg oppgraderte Helmet, så tenkte det var like greit å få fikset det nå.
=> defaultRoute and Html to tsx. Fix graphql hydration

.github/workflows/ci.yml, .github/workflows/release.yml
=> Bump github actions versions

src/containers/ListingPage/ListingContainer.tsx, src/graphqlTypes.ts, src/schema.graphql
Depends on https://github.com/NDLANO/graphql-api/pull/340
Fixes NDLANO/Issues#3600
Passer på at kun gammel type forklaringer sendes til endepunktet.
=> Sends concept-type to avoid fetching gloss.

src/server/contentSecurityPolicy.js
https://github.com/NDLANO/Issues/issues/3710
=> Remove hotjar

.github/workflows/ci.yml, Dockerfile, package.json
Kjørte denne lokalt og det funka som det skulle.
=> Use node 18.18

README.md, package.json, src/containers/ListingPage/ListingContainer.tsx, src/containers/ListingPage/ListingView.tsx, src/util/apiHelpers.ts, tsconfig.json, yarn.lock
Dedupliserte pakker. De fjernede propsa i ListView finnes ikke i selve pakken
=> Bump node types to 20
